// Code generated by Slice Machine. DO NOT EDIT.

import BannerSection from "./BannerSection/index.svelte";
import BannerSections from "./BannerSections/index.svelte";
import BenefitSection from "./BenefitSection/index.svelte";
import BrandSection from "./BrandSection/index.svelte";
import CommonBannerSection from "./CommonBannerSection/index.svelte";
import CopyrightSection from "./CopyrightSection/index.svelte";
import HomeProductSection from "./HomeProductSection/index.svelte";
import IdeaSection from "./IdeaSection/index.svelte";
import InfoSection from "./InfoSection/index.svelte";
import LogoSection from "./LogoSection/index.svelte";
import MenusSection from "./MenusSection/index.svelte";
import ProductMenuSection from "./ProductMenuSection/index.svelte";
import QuestionSection from "./QuestionSection/index.svelte";
import ShopBannerSection from "./ShopBannerSection/index.svelte";
import ShopFeatureSection from "./ShopFeatureSection/index.svelte";
import ShopProductSection from "./ShopProductSection/index.svelte";
import SocialSection from "./SocialSection/index.svelte";
import TrendSection from "./TrendSection/index.svelte";
import VariantsSection from "./VariantsSection/index.svelte";
import WorkSection from "./WorkSection/index.svelte";

export const components = {
  banner_section: BannerSection,
  banner_sections: BannerSections,
  benefit_section: BenefitSection,
  brand_section: BrandSection,
  common_banner_section: CommonBannerSection,
  copyright_section: CopyrightSection,
  home_product_section: HomeProductSection,
  idea_section: IdeaSection,
  info_section: InfoSection,
  logo_section: LogoSection,
  menus_section: MenusSection,
  product_menu_section: ProductMenuSection,
  question_section: QuestionSection,
  shop_banner_section: ShopBannerSection,
  shop_feature_section: ShopFeatureSection,
  shop_product_section: ShopProductSection,
  social_section: SocialSection,
  trend_section: TrendSection,
  variants_section: VariantsSection,
  work_section: WorkSection,
};
