// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlices1Slice = BannerSectionsSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices1[]
   * - **Tab**: Banner Section
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<AboutDocumentDataSlices1Slice>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

type CartPageDocumentDataSlices1Slice = CommonBannerSectionSlice;

/**
 * Content for Cart Page documents
 */
interface CartPageDocumentData {
  /**
   * Slice Zone field in *Cart Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: cart_page.slices1[]
   * - **Tab**: Banner Section
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<CartPageDocumentDataSlices1Slice>;
}

/**
 * Cart Page document from Prismic
 *
 * - **API ID**: `cart_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CartPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CartPageDocumentData>,
    "cart_page",
    Lang
  >;

type FooerDocumentDataSlices1Slice = InfoSectionSlice;

type FooerDocumentDataSlices2Slice = CopyrightSectionSlice;

type FooerDocumentDataSlices3Slice = ProductMenuSectionSlice;

type FooerDocumentDataSlices4Slice = SocialSectionSlice;

/**
 * Content for Fooer documents
 */
interface FooerDocumentData {
  /**
   * Logo field in *Fooer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fooer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Info Title field in *Fooer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fooer.info_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info_title: prismic.KeyTextField;

  /**
   * Shop Title field in *Fooer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fooer.shop_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  shop_title: prismic.KeyTextField;

  /**
   * Title field in *Fooer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fooer.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField /**
   * Slice Zone field in *Fooer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: fooer.slices1[]
   * - **Tab**: Info Section
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices1: prismic.SliceZone<FooerDocumentDataSlices1Slice> /**
   * Slice Zone field in *Fooer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: fooer.slices2[]
   * - **Tab**: Copyright Section
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices2: prismic.SliceZone<FooerDocumentDataSlices2Slice> /**
   * Slice Zone field in *Fooer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: fooer.slices3[]
   * - **Tab**: Product Menu Section
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices3: prismic.SliceZone<FooerDocumentDataSlices3Slice> /**
   * Slice Zone field in *Fooer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: fooer.slices4[]
   * - **Tab**: Social Section
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices4: prismic.SliceZone<FooerDocumentDataSlices4Slice>;
}

/**
 * Fooer document from Prismic
 *
 * - **API ID**: `fooer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<FooerDocumentData>, "fooer", Lang>;

type HeaderDocumentDataSlices1Slice = MenusSectionSlice;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never> /**
   * Slice Zone field in *Header*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: header.slices1[]
   * - **Tab**: Menu Section
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices1: prismic.SliceZone<HeaderDocumentDataSlices1Slice>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type HomePageDocumentDataSlices1Slice = BannerSectionSlice;

type HomePageDocumentDataSlices2Slice = VariantsSectionSlice;

type HomePageDocumentDataSlices3Slice = BrandSectionSlice;

type HomePageDocumentDataSlices4Slice = TrendSectionSlice;

type HomePageDocumentDataSlices5Slice = IdeaSectionSlice;

type HomePageDocumentDataSlices6Slice = BenefitSectionSlice;

type HomePageDocumentDataSlices7Slice = LogoSectionSlice;

type HomePageDocumentDataSlices8Slice = WorkSectionSlice;

type HomePageDocumentDataSlices9Slice = QuestionSectionSlice;

type HomePageDocumentDataSlices10Slice = HomeProductSectionSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices1[]
   * - **Tab**: Banner Section
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<HomePageDocumentDataSlices1Slice> /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices2[]
   * - **Tab**: Variants Section
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices2: prismic.SliceZone<HomePageDocumentDataSlices2Slice> /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices3[]
   * - **Tab**: Brand Section
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices3: prismic.SliceZone<HomePageDocumentDataSlices3Slice> /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices4[]
   * - **Tab**: Trend Section
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices4: prismic.SliceZone<HomePageDocumentDataSlices4Slice> /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices5[]
   * - **Tab**: Idea Section
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices5: prismic.SliceZone<HomePageDocumentDataSlices5Slice> /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices6[]
   * - **Tab**: Benefit Section
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices6: prismic.SliceZone<HomePageDocumentDataSlices6Slice> /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices7[]
   * - **Tab**: Logo Section
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices7: prismic.SliceZone<HomePageDocumentDataSlices7Slice> /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices8[]
   * - **Tab**: Work Section
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices8: prismic.SliceZone<HomePageDocumentDataSlices8Slice> /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices9[]
   * - **Tab**: Question Section
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices9: prismic.SliceZone<HomePageDocumentDataSlices9Slice> /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices10[]
   * - **Tab**: Home Product Section
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices10: prismic.SliceZone<HomePageDocumentDataSlices10Slice>;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type ShopDocumentDataSlices1Slice = ShopBannerSectionSlice;

type ShopDocumentDataSlices2Slice = ShopFeatureSectionSlice;

type ShopDocumentDataSlices3Slice = ShopProductSectionSlice;

/**
 * Content for Shop documents
 */
interface ShopDocumentData {
  /**
   * Slice Zone field in *Shop*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: shop.slices1[]
   * - **Tab**: Banner Section
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<ShopDocumentDataSlices1Slice> /**
   * Slice Zone field in *Shop*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: shop.slices2[]
   * - **Tab**: Feature Section
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices2: prismic.SliceZone<ShopDocumentDataSlices2Slice> /**
   * Slice Zone field in *Shop*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: shop.slices3[]
   * - **Tab**: Shop Product Section
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices3: prismic.SliceZone<ShopDocumentDataSlices3Slice>;
}

/**
 * Shop document from Prismic
 *
 * - **API ID**: `shop`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ShopDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<ShopDocumentData>, "shop", Lang>;

export type AllDocumentTypes =
  | AboutDocument
  | CartPageDocument
  | FooerDocument
  | HeaderDocument
  | HomeDocument
  | HomePageDocument
  | ShopDocument;

/**
 * Primary content in *BannerSection → Default → Primary*
 */
export interface BannerSectionSliceDefaultPrimary {
  /**
   * Left Video Link field in *BannerSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_section.default.primary.left_video_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  left_video_link: prismic.LinkField;

  /**
   * Right Video Link field in *BannerSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_section.default.primary.right_video_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  right_video_link: prismic.LinkField;

  /**
   * Mobile Video Link field in *BannerSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_section.default.primary.mobile_video_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  mobile_video_link: prismic.LinkField;
}

/**
 * Default variation for BannerSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BannerSection*
 */
type BannerSectionSliceVariation = BannerSectionSliceDefault;

/**
 * BannerSection Shared Slice
 *
 * - **API ID**: `banner_section`
 * - **Description**: BannerSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSectionSlice = prismic.SharedSlice<
  "banner_section",
  BannerSectionSliceVariation
>;

/**
 * Primary content in *BannerSections → Default → Primary*
 */
export interface BannerSectionsSliceDefaultPrimary {
  /**
   * Title field in *BannerSections → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_sections.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for BannerSections Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSectionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSectionsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BannerSections*
 */
type BannerSectionsSliceVariation = BannerSectionsSliceDefault;

/**
 * BannerSections Shared Slice
 *
 * - **API ID**: `banner_sections`
 * - **Description**: BannerSections
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSectionsSlice = prismic.SharedSlice<
  "banner_sections",
  BannerSectionsSliceVariation
>;

/**
 * Item in *BenefitSection → Default → Primary → Benefit Section List*
 */
export interface BenefitSectionSliceDefaultPrimaryBenefitSectionListItem {
  /**
   * Image field in *BenefitSection → Default → Primary → Benefit Section List*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: benefit_section.default.primary.benefit_section_list[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *BenefitSection → Default → Primary → Benefit Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefit_section.default.primary.benefit_section_list[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *BenefitSection → Default → Primary → Benefit Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefit_section.default.primary.benefit_section_list[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Primary content in *BenefitSection → Default → Primary*
 */
export interface BenefitSectionSliceDefaultPrimary {
  /**
   * Preview Background Image  field in *BenefitSection → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: benefit_section.default.primary.preview_background_image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  preview_background_image: prismic.LinkToMediaField;

  /**
   * Title field in *BenefitSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefit_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *BenefitSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefit_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Benefit Section List field in *BenefitSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: benefit_section.default.primary.benefit_section_list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  benefit_section_list: prismic.GroupField<
    Simplify<BenefitSectionSliceDefaultPrimaryBenefitSectionListItem>
  >;
}

/**
 * Default variation for BenefitSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BenefitSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BenefitSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BenefitSection*
 */
type BenefitSectionSliceVariation = BenefitSectionSliceDefault;

/**
 * BenefitSection Shared Slice
 *
 * - **API ID**: `benefit_section`
 * - **Description**: BenefitSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BenefitSectionSlice = prismic.SharedSlice<
  "benefit_section",
  BenefitSectionSliceVariation
>;

/**
 * Primary content in *BrandSection → Default → Primary*
 */
export interface BrandSectionSliceDefaultPrimary {
  /**
   * Logo1 field in *BrandSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_section.default.primary.logo1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo1: prismic.ImageField<never>;

  /**
   * Logo2 field in *BrandSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_section.default.primary.logo2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo2: prismic.ImageField<never>;

  /**
   * Title field in *BrandSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Btn Text field in *BrandSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_section.default.primary.btn_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btn_text: prismic.KeyTextField;

  /**
   * Background Image field in *BrandSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_section.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Preview Background Image field in *BrandSection → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_section.default.primary.preview_background_image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  preview_background_image: prismic.LinkToMediaField;
}

/**
 * Default variation for BrandSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BrandSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BrandSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BrandSection*
 */
type BrandSectionSliceVariation = BrandSectionSliceDefault;

/**
 * BrandSection Shared Slice
 *
 * - **API ID**: `brand_section`
 * - **Description**: BrandSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BrandSectionSlice = prismic.SharedSlice<
  "brand_section",
  BrandSectionSliceVariation
>;

/**
 * Item in *CommonBannerSection → Default → Primary → Common Banner Section List*
 */
export interface CommonBannerSectionSliceDefaultPrimaryCommonBannerSectionListItem {
  /**
   * Breadcrumb Name field in *CommonBannerSection → Default → Primary → Common Banner Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: common_banner_section.default.primary.common_banner_section_list[].breadcrumb_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  breadcrumb_name: prismic.KeyTextField;

  /**
   * Breadcrumb Uid field in *CommonBannerSection → Default → Primary → Common Banner Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: common_banner_section.default.primary.common_banner_section_list[].breadcrumb_uid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  breadcrumb_uid: prismic.KeyTextField;
}

/**
 * Primary content in *CommonBannerSection → Default → Primary*
 */
export interface CommonBannerSectionSliceDefaultPrimary {
  /**
   * Title field in *CommonBannerSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: common_banner_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Svg Animation Text field in *CommonBannerSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: common_banner_section.default.primary.svg_animation_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  svg_animation_text: prismic.KeyTextField;

  /**
   * Background Image field in *CommonBannerSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: common_banner_section.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Common Banner Section List field in *CommonBannerSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: common_banner_section.default.primary.common_banner_section_list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  common_banner_section_list: prismic.GroupField<
    Simplify<CommonBannerSectionSliceDefaultPrimaryCommonBannerSectionListItem>
  >;
}

/**
 * Default variation for CommonBannerSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CommonBannerSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CommonBannerSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CommonBannerSection*
 */
type CommonBannerSectionSliceVariation = CommonBannerSectionSliceDefault;

/**
 * CommonBannerSection Shared Slice
 *
 * - **API ID**: `common_banner_section`
 * - **Description**: CommonBannerSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CommonBannerSectionSlice = prismic.SharedSlice<
  "common_banner_section",
  CommonBannerSectionSliceVariation
>;

/**
 * Primary content in *CopyrightSection → Default → Primary*
 */
export interface CopyrightSectionSliceDefaultPrimary {
  /**
   * Site Name field in *CopyrightSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: copyright_section.default.primary.site_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_name: prismic.KeyTextField;

  /**
   * Copyright Text field in *CopyrightSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: copyright_section.default.primary.copyright_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright_text: prismic.KeyTextField;
}

/**
 * Default variation for CopyrightSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CopyrightSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CopyrightSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CopyrightSection*
 */
type CopyrightSectionSliceVariation = CopyrightSectionSliceDefault;

/**
 * CopyrightSection Shared Slice
 *
 * - **API ID**: `copyright_section`
 * - **Description**: CopyrightSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CopyrightSectionSlice = prismic.SharedSlice<
  "copyright_section",
  CopyrightSectionSliceVariation
>;

/**
 * Primary content in *HomeProductSection → Default → Primary*
 */
export interface HomeProductSectionSliceDefaultPrimary {
  /**
   * Title field in *HomeProductSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_product_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Preview Background Image field in *HomeProductSection → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: home_product_section.default.primary.preview_background_image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  preview_background_image: prismic.LinkToMediaField;
}

/**
 * Default variation for HomeProductSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeProductSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeProductSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeProductSection*
 */
type HomeProductSectionSliceVariation = HomeProductSectionSliceDefault;

/**
 * HomeProductSection Shared Slice
 *
 * - **API ID**: `home_product_section`
 * - **Description**: HomeProductSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeProductSectionSlice = prismic.SharedSlice<
  "home_product_section",
  HomeProductSectionSliceVariation
>;

/**
 * Item in *IdeaSection → Default → Primary → Idea Section List*
 */
export interface IdeaSectionSliceDefaultPrimaryIdeaSectionListItem {
  /**
   * Image field in *IdeaSection → Default → Primary → Idea Section List*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: idea_section.default.primary.idea_section_list[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *IdeaSection → Default → Primary → Idea Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: idea_section.default.primary.idea_section_list[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Last Name field in *IdeaSection → Default → Primary → Idea Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: idea_section.default.primary.idea_section_list[].last_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  last_name: prismic.KeyTextField;

  /**
   * Description field in *IdeaSection → Default → Primary → Idea Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: idea_section.default.primary.idea_section_list[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *IdeaSection → Default → Primary*
 */
export interface IdeaSectionSliceDefaultPrimary {
  /**
   * Preview Background Image field in *IdeaSection → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: idea_section.default.primary.preview_background_image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  preview_background_image: prismic.LinkToMediaField;

  /**
   * Title field in *IdeaSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: idea_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Paragraph field in *IdeaSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: idea_section.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;

  /**
   * Logo field in *IdeaSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: idea_section.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Background Image field in *IdeaSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: idea_section.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Idea Section List field in *IdeaSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: idea_section.default.primary.idea_section_list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  idea_section_list: prismic.GroupField<
    Simplify<IdeaSectionSliceDefaultPrimaryIdeaSectionListItem>
  >;
}

/**
 * Default variation for IdeaSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IdeaSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IdeaSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IdeaSection*
 */
type IdeaSectionSliceVariation = IdeaSectionSliceDefault;

/**
 * IdeaSection Shared Slice
 *
 * - **API ID**: `idea_section`
 * - **Description**: IdeaSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IdeaSectionSlice = prismic.SharedSlice<
  "idea_section",
  IdeaSectionSliceVariation
>;

/**
 * Item in *InfoSection → Default → Primary → Info Section List*
 */
export interface InfoSectionSliceDefaultPrimaryInfoSectionListItem {
  /**
   * Menu Name field in *InfoSection → Default → Primary → Info Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_section.default.primary.info_section_list[].menu_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_name: prismic.KeyTextField;

  /**
   * Menu Uid field in *InfoSection → Default → Primary → Info Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_section.default.primary.info_section_list[].menu_uid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_uid: prismic.KeyTextField;
}

/**
 * Primary content in *InfoSection → Default → Primary*
 */
export interface InfoSectionSliceDefaultPrimary {
  /**
   * Info Section List field in *InfoSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: info_section.default.primary.info_section_list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  info_section_list: prismic.GroupField<
    Simplify<InfoSectionSliceDefaultPrimaryInfoSectionListItem>
  >;
}

/**
 * Default variation for InfoSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InfoSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *InfoSection*
 */
type InfoSectionSliceVariation = InfoSectionSliceDefault;

/**
 * InfoSection Shared Slice
 *
 * - **API ID**: `info_section`
 * - **Description**: InfoSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoSectionSlice = prismic.SharedSlice<
  "info_section",
  InfoSectionSliceVariation
>;

/**
 * Item in *LogoSection → Default → Primary → Logo Section List*
 */
export interface LogoSectionSliceDefaultPrimaryLogoSectionListItem {
  /**
   * Logo field in *LogoSection → Default → Primary → Logo Section List*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_section.default.primary.logo_section_list[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Primary content in *LogoSection → Default → Primary*
 */
export interface LogoSectionSliceDefaultPrimary {
  /**
   * Preview Background Image field in *LogoSection → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_section.default.primary.preview_background_image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  preview_background_image: prismic.LinkToMediaField;

  /**
   * Logo Section List field in *LogoSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_section.default.primary.logo_section_list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  logo_section_list: prismic.GroupField<
    Simplify<LogoSectionSliceDefaultPrimaryLogoSectionListItem>
  >;
}

/**
 * Default variation for LogoSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LogoSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LogoSection*
 */
type LogoSectionSliceVariation = LogoSectionSliceDefault;

/**
 * LogoSection Shared Slice
 *
 * - **API ID**: `logo_section`
 * - **Description**: LogoSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoSectionSlice = prismic.SharedSlice<
  "logo_section",
  LogoSectionSliceVariation
>;

/**
 * Item in *MenusSection → Default → Primary → Menus Section List*
 */
export interface MenusSectionSliceDefaultPrimaryMenusSectionListItem {
  /**
   * Menu Name field in *MenusSection → Default → Primary → Menus Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menus_section.default.primary.menus_section_list[].menu_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_name: prismic.KeyTextField;

  /**
   * Menu Uid field in *MenusSection → Default → Primary → Menus Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menus_section.default.primary.menus_section_list[].menu_uid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_uid: prismic.KeyTextField;
}

/**
 * Primary content in *MenusSection → Default → Primary*
 */
export interface MenusSectionSliceDefaultPrimary {
  /**
   * Menus Section List field in *MenusSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menus_section.default.primary.menus_section_list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menus_section_list: prismic.GroupField<
    Simplify<MenusSectionSliceDefaultPrimaryMenusSectionListItem>
  >;
}

/**
 * Default variation for MenusSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenusSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MenusSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MenusSection*
 */
type MenusSectionSliceVariation = MenusSectionSliceDefault;

/**
 * MenusSection Shared Slice
 *
 * - **API ID**: `menus_section`
 * - **Description**: MenusSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenusSectionSlice = prismic.SharedSlice<
  "menus_section",
  MenusSectionSliceVariation
>;

/**
 * Item in *ProductMenuSection → Default → Primary → Product Menu Section List*
 */
export interface ProductMenuSectionSliceDefaultPrimaryProductMenuSectionListItem {
  /**
   * Menu name field in *ProductMenuSection → Default → Primary → Product Menu Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_menu_section.default.primary.product_menu_section_list[].menu_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_name: prismic.KeyTextField;

  /**
   * Menu Uid field in *ProductMenuSection → Default → Primary → Product Menu Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_menu_section.default.primary.product_menu_section_list[].menu_uid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_uid: prismic.KeyTextField;
}

/**
 * Primary content in *ProductMenuSection → Default → Primary*
 */
export interface ProductMenuSectionSliceDefaultPrimary {
  /**
   * Product Menu Section List field in *ProductMenuSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product_menu_section.default.primary.product_menu_section_list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  product_menu_section_list: prismic.GroupField<
    Simplify<ProductMenuSectionSliceDefaultPrimaryProductMenuSectionListItem>
  >;
}

/**
 * Default variation for ProductMenuSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductMenuSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductMenuSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProductMenuSection*
 */
type ProductMenuSectionSliceVariation = ProductMenuSectionSliceDefault;

/**
 * ProductMenuSection Shared Slice
 *
 * - **API ID**: `product_menu_section`
 * - **Description**: ProductMenuSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductMenuSectionSlice = prismic.SharedSlice<
  "product_menu_section",
  ProductMenuSectionSliceVariation
>;

/**
 * Item in *QuestionSection → Default → Primary → Question Section List*
 */
export interface QuestionSectionSliceDefaultPrimaryQuestionSectionListItem {
  /**
   * Question field in *QuestionSection → Default → Primary → Question Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: question_section.default.primary.question_section_list[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *QuestionSection → Default → Primary → Question Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: question_section.default.primary.question_section_list[].answer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer: prismic.KeyTextField;
}

/**
 * Primary content in *QuestionSection → Default → Primary*
 */
export interface QuestionSectionSliceDefaultPrimary {
  /**
   * Preview Background Image field in *QuestionSection → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: question_section.default.primary.preview_background_image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  preview_background_image: prismic.LinkToMediaField;

  /**
   * Title field in *QuestionSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: question_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *QuestionSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: question_section.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Question Section List field in *QuestionSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: question_section.default.primary.question_section_list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  question_section_list: prismic.GroupField<
    Simplify<QuestionSectionSliceDefaultPrimaryQuestionSectionListItem>
  >;
}

/**
 * Default variation for QuestionSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuestionSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuestionSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *QuestionSection*
 */
type QuestionSectionSliceVariation = QuestionSectionSliceDefault;

/**
 * QuestionSection Shared Slice
 *
 * - **API ID**: `question_section`
 * - **Description**: QuestionSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuestionSectionSlice = prismic.SharedSlice<
  "question_section",
  QuestionSectionSliceVariation
>;

/**
 * Item in *ShopBannerSection → Default → Primary → Shop Banner Section List*
 */
export interface ShopBannerSectionSliceDefaultPrimaryShopBannerSectionListItem {
  /**
   * Breadcrumb Name field in *ShopBannerSection → Default → Primary → Shop Banner Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_banner_section.default.primary.shop_banner_section_list[].breadcrumb_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  breadcrumb_name: prismic.KeyTextField;

  /**
   * Breadcrumb UID field in *ShopBannerSection → Default → Primary → Shop Banner Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_banner_section.default.primary.shop_banner_section_list[].breadcrumb_uid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  breadcrumb_uid: prismic.KeyTextField;
}

/**
 * Primary content in *ShopBannerSection → Default → Primary*
 */
export interface ShopBannerSectionSliceDefaultPrimary {
  /**
   * Title field in *ShopBannerSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_banner_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *ShopBannerSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_banner_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Svg Animaton Text field in *ShopBannerSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_banner_section.default.primary.svg_animaton_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  svg_animaton_text: prismic.KeyTextField;

  /**
   * Shop Banner Section List field in *ShopBannerSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_banner_section.default.primary.shop_banner_section_list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  shop_banner_section_list: prismic.GroupField<
    Simplify<ShopBannerSectionSliceDefaultPrimaryShopBannerSectionListItem>
  >;
}

/**
 * Default variation for ShopBannerSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShopBannerSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ShopBannerSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ShopBannerSection*
 */
type ShopBannerSectionSliceVariation = ShopBannerSectionSliceDefault;

/**
 * ShopBannerSection Shared Slice
 *
 * - **API ID**: `shop_banner_section`
 * - **Description**: ShopBannerSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShopBannerSectionSlice = prismic.SharedSlice<
  "shop_banner_section",
  ShopBannerSectionSliceVariation
>;

/**
 * Primary content in *ShopFeatureSection → Default → Primary*
 */
export interface ShopFeatureSectionSliceDefaultPrimary {
  /**
   * Title field in *ShopFeatureSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_feature_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ShopFeatureSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_feature_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Image field in *ShopFeatureSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_feature_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Background Image field in *ShopFeatureSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_feature_section.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for ShopFeatureSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShopFeatureSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ShopFeatureSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ShopFeatureSection*
 */
type ShopFeatureSectionSliceVariation = ShopFeatureSectionSliceDefault;

/**
 * ShopFeatureSection Shared Slice
 *
 * - **API ID**: `shop_feature_section`
 * - **Description**: ShopFeatureSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShopFeatureSectionSlice = prismic.SharedSlice<
  "shop_feature_section",
  ShopFeatureSectionSliceVariation
>;

/**
 * Primary content in *ShopProductSection → Default → Primary*
 */
export interface ShopProductSectionSliceDefaultPrimary {
  /**
   * Image field in *ShopProductSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_product_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Background field in *ShopProductSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_product_section.default.primary.image_background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_background: prismic.ImageField<never>;

  /**
   * Title field in *ShopProductSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_product_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for ShopProductSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShopProductSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ShopProductSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ShopProductSection*
 */
type ShopProductSectionSliceVariation = ShopProductSectionSliceDefault;

/**
 * ShopProductSection Shared Slice
 *
 * - **API ID**: `shop_product_section`
 * - **Description**: ShopProductSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShopProductSectionSlice = prismic.SharedSlice<
  "shop_product_section",
  ShopProductSectionSliceVariation
>;

/**
 * Item in *SocialSection → Default → Primary → Social Section List*
 */
export interface SocialSectionSliceDefaultPrimarySocialSectionListItem {
  /**
   * Social Svg icon text field in *SocialSection → Default → Primary → Social Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_section.default.primary.social_section_list[].social_svg_icon_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  social_svg_icon_text: prismic.KeyTextField;

  /**
   * Class Name field in *SocialSection → Default → Primary → Social Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_section.default.primary.social_section_list[].class_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  class_name: prismic.KeyTextField;

  /**
   * Social Media Url field in *SocialSection → Default → Primary → Social Section List*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: social_section.default.primary.social_section_list[].social_media_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_media_url: prismic.LinkField;
}

/**
 * Primary content in *SocialSection → Default → Primary*
 */
export interface SocialSectionSliceDefaultPrimary {
  /**
   * Title field in *SocialSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Social Section List field in *SocialSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: social_section.default.primary.social_section_list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_section_list: prismic.GroupField<
    Simplify<SocialSectionSliceDefaultPrimarySocialSectionListItem>
  >;
}

/**
 * Default variation for SocialSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SocialSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SocialSection*
 */
type SocialSectionSliceVariation = SocialSectionSliceDefault;

/**
 * SocialSection Shared Slice
 *
 * - **API ID**: `social_section`
 * - **Description**: SocialSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialSectionSlice = prismic.SharedSlice<
  "social_section",
  SocialSectionSliceVariation
>;

/**
 * Primary content in *TrendSection → Default → Primary*
 */
export interface TrendSectionSliceDefaultPrimary {
  /**
   * Preview Background Image field in *TrendSection → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: trend_section.default.primary.preview_background_mage
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  preview_background_mage: prismic.LinkToMediaField;

  /**
   * Trend Lottie Json field in *TrendSection → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: trend_section.default.primary.trend_lottie_json
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  trend_lottie_json: prismic.LinkToMediaField;

  /**
   * First Title field in *TrendSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trend_section.default.primary.first_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  first_title: prismic.KeyTextField;

  /**
   * Banner Image field in *TrendSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: trend_section.default.primary.banner_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner_image: prismic.ImageField<never>;

  /**
   * Btn Text field in *TrendSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trend_section.default.primary.btn_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btn_text: prismic.KeyTextField;

  /**
   * Title field in *TrendSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trend_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Paragraph field in *TrendSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trend_section.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Default variation for TrendSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TrendSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TrendSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TrendSection*
 */
type TrendSectionSliceVariation = TrendSectionSliceDefault;

/**
 * TrendSection Shared Slice
 *
 * - **API ID**: `trend_section`
 * - **Description**: TrendSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TrendSectionSlice = prismic.SharedSlice<
  "trend_section",
  TrendSectionSliceVariation
>;

/**
 * Item in *VariantsSection → Default → Primary → Variants Section List*
 */
export interface VariantsSectionSliceDefaultPrimaryVariantsSectionListItem {
  /**
   * Product Title field in *VariantsSection → Default → Primary → Variants Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: variants_section.default.primary.variants_section_list[].product_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  product_title: prismic.KeyTextField;

  /**
   * Image field in *VariantsSection → Default → Primary → Variants Section List*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: variants_section.default.primary.variants_section_list[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Description field in *VariantsSection → Default → Primary → Variants Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: variants_section.default.primary.variants_section_list[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Lottie Json field in *VariantsSection → Default → Primary → Variants Section List*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: variants_section.default.primary.variants_section_list[].lottie_json
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lottie_json: prismic.LinkToMediaField;

  /**
   * Mobile Lottie Json field in *VariantsSection → Default → Primary → Variants Section List*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: variants_section.default.primary.variants_section_list[].mobile_lottie_json
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  mobile_lottie_json: prismic.LinkToMediaField;

  /**
   * Position field in *VariantsSection → Default → Primary → Variants Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: variants_section.default.primary.variants_section_list[].position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;
}

/**
 * Primary content in *VariantsSection → Default → Primary*
 */
export interface VariantsSectionSliceDefaultPrimary {
  /**
   * Background Image field in *VariantsSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: variants_section.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Preview Background Image field in *VariantsSection → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: variants_section.default.primary.preview_background_image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  preview_background_image: prismic.LinkToMediaField;

  /**
   * Title field in *VariantsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: variants_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *VariantsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: variants_section.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;

  /**
   * Lottie Loader field in *VariantsSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: variants_section.default.primary.lottie_loader
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  lottie_loader: prismic.ImageField<never>;

  /**
   * Mobile Lottie Json field in *VariantsSection → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: variants_section.default.primary.mobile_lottie_json
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  mobile_lottie_json: prismic.LinkToMediaField;

  /**
   * Image Background field in *VariantsSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: variants_section.default.primary.image_background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_background: prismic.ImageField<never>;

  /**
   * Variants Section List field in *VariantsSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: variants_section.default.primary.variants_section_list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  variants_section_list: prismic.GroupField<
    Simplify<VariantsSectionSliceDefaultPrimaryVariantsSectionListItem>
  >;
}

/**
 * Default variation for VariantsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VariantsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VariantsSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VariantsSection*
 */
type VariantsSectionSliceVariation = VariantsSectionSliceDefault;

/**
 * VariantsSection Shared Slice
 *
 * - **API ID**: `variants_section`
 * - **Description**: VariantsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VariantsSectionSlice = prismic.SharedSlice<
  "variants_section",
  VariantsSectionSliceVariation
>;

/**
 * Item in *WorkSection → Default → Primary → Work Section List*
 */
export interface WorkSectionSliceDefaultPrimaryWorkSectionListItem {
  /**
   * Title field in *WorkSection → Default → Primary → Work Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_section.default.primary.work_section_list[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *WorkSection → Default → Primary → Work Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_section.default.primary.work_section_list[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * Category field in *WorkSection → Default → Primary → Work Section List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_section.default.primary.work_section_list[].category
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category: prismic.KeyTextField;

  /**
   * Image field in *WorkSection → Default → Primary → Work Section List*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: work_section.default.primary.work_section_list[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *WorkSection → Default → Primary*
 */
export interface WorkSectionSliceDefaultPrimary {
  /**
   * Preview Background Image field in *WorkSection → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: work_section.default.primary.preview_background_image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  preview_background_image: prismic.LinkToMediaField;

  /**
   * Title field in *WorkSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *WorkSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Work Section List field in *WorkSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work_section.default.primary.work_section_list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  work_section_list: prismic.GroupField<
    Simplify<WorkSectionSliceDefaultPrimaryWorkSectionListItem>
  >;
}

/**
 * Default variation for WorkSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorkSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WorkSection*
 */
type WorkSectionSliceVariation = WorkSectionSliceDefault;

/**
 * WorkSection Shared Slice
 *
 * - **API ID**: `work_section`
 * - **Description**: WorkSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkSectionSlice = prismic.SharedSlice<
  "work_section",
  WorkSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlices1Slice,
      CartPageDocument,
      CartPageDocumentData,
      CartPageDocumentDataSlices1Slice,
      FooerDocument,
      FooerDocumentData,
      FooerDocumentDataSlices1Slice,
      FooerDocumentDataSlices2Slice,
      FooerDocumentDataSlices3Slice,
      FooerDocumentDataSlices4Slice,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataSlices1Slice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlices1Slice,
      HomePageDocumentDataSlices2Slice,
      HomePageDocumentDataSlices3Slice,
      HomePageDocumentDataSlices4Slice,
      HomePageDocumentDataSlices5Slice,
      HomePageDocumentDataSlices6Slice,
      HomePageDocumentDataSlices7Slice,
      HomePageDocumentDataSlices8Slice,
      HomePageDocumentDataSlices9Slice,
      HomePageDocumentDataSlices10Slice,
      ShopDocument,
      ShopDocumentData,
      ShopDocumentDataSlices1Slice,
      ShopDocumentDataSlices2Slice,
      ShopDocumentDataSlices3Slice,
      AllDocumentTypes,
      BannerSectionSlice,
      BannerSectionSliceDefaultPrimary,
      BannerSectionSliceVariation,
      BannerSectionSliceDefault,
      BannerSectionsSlice,
      BannerSectionsSliceDefaultPrimary,
      BannerSectionsSliceVariation,
      BannerSectionsSliceDefault,
      BenefitSectionSlice,
      BenefitSectionSliceDefaultPrimaryBenefitSectionListItem,
      BenefitSectionSliceDefaultPrimary,
      BenefitSectionSliceVariation,
      BenefitSectionSliceDefault,
      BrandSectionSlice,
      BrandSectionSliceDefaultPrimary,
      BrandSectionSliceVariation,
      BrandSectionSliceDefault,
      CommonBannerSectionSlice,
      CommonBannerSectionSliceDefaultPrimaryCommonBannerSectionListItem,
      CommonBannerSectionSliceDefaultPrimary,
      CommonBannerSectionSliceVariation,
      CommonBannerSectionSliceDefault,
      CopyrightSectionSlice,
      CopyrightSectionSliceDefaultPrimary,
      CopyrightSectionSliceVariation,
      CopyrightSectionSliceDefault,
      HomeProductSectionSlice,
      HomeProductSectionSliceDefaultPrimary,
      HomeProductSectionSliceVariation,
      HomeProductSectionSliceDefault,
      IdeaSectionSlice,
      IdeaSectionSliceDefaultPrimaryIdeaSectionListItem,
      IdeaSectionSliceDefaultPrimary,
      IdeaSectionSliceVariation,
      IdeaSectionSliceDefault,
      InfoSectionSlice,
      InfoSectionSliceDefaultPrimaryInfoSectionListItem,
      InfoSectionSliceDefaultPrimary,
      InfoSectionSliceVariation,
      InfoSectionSliceDefault,
      LogoSectionSlice,
      LogoSectionSliceDefaultPrimaryLogoSectionListItem,
      LogoSectionSliceDefaultPrimary,
      LogoSectionSliceVariation,
      LogoSectionSliceDefault,
      MenusSectionSlice,
      MenusSectionSliceDefaultPrimaryMenusSectionListItem,
      MenusSectionSliceDefaultPrimary,
      MenusSectionSliceVariation,
      MenusSectionSliceDefault,
      ProductMenuSectionSlice,
      ProductMenuSectionSliceDefaultPrimaryProductMenuSectionListItem,
      ProductMenuSectionSliceDefaultPrimary,
      ProductMenuSectionSliceVariation,
      ProductMenuSectionSliceDefault,
      QuestionSectionSlice,
      QuestionSectionSliceDefaultPrimaryQuestionSectionListItem,
      QuestionSectionSliceDefaultPrimary,
      QuestionSectionSliceVariation,
      QuestionSectionSliceDefault,
      ShopBannerSectionSlice,
      ShopBannerSectionSliceDefaultPrimaryShopBannerSectionListItem,
      ShopBannerSectionSliceDefaultPrimary,
      ShopBannerSectionSliceVariation,
      ShopBannerSectionSliceDefault,
      ShopFeatureSectionSlice,
      ShopFeatureSectionSliceDefaultPrimary,
      ShopFeatureSectionSliceVariation,
      ShopFeatureSectionSliceDefault,
      ShopProductSectionSlice,
      ShopProductSectionSliceDefaultPrimary,
      ShopProductSectionSliceVariation,
      ShopProductSectionSliceDefault,
      SocialSectionSlice,
      SocialSectionSliceDefaultPrimarySocialSectionListItem,
      SocialSectionSliceDefaultPrimary,
      SocialSectionSliceVariation,
      SocialSectionSliceDefault,
      TrendSectionSlice,
      TrendSectionSliceDefaultPrimary,
      TrendSectionSliceVariation,
      TrendSectionSliceDefault,
      VariantsSectionSlice,
      VariantsSectionSliceDefaultPrimaryVariantsSectionListItem,
      VariantsSectionSliceDefaultPrimary,
      VariantsSectionSliceVariation,
      VariantsSectionSliceDefault,
      WorkSectionSlice,
      WorkSectionSliceDefaultPrimaryWorkSectionListItem,
      WorkSectionSliceDefaultPrimary,
      WorkSectionSliceVariation,
      WorkSectionSliceDefault,
    };
  }
}
